require "#{File.dirname(__FILE__)}/../../core/vagrant/Vagrantfile.core"

Provider.core(memory: 2048, cpus: 1)

Environment.new(name: 'sql.local') do |environment|
  WindowsSampleVM.new(environment, name: '14d', box: 'gusztavvargadr/w16s-sql14d')
end
